// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFqWZrzxXeP0NC-_rZqVVh32oPTYzcOKk',
    appId: '1:97689262276:android:d393a6bfb42dbdf6cb1191',
    messagingSenderId: '97689262276',
    projectId: 'project-cadastro-revavon',
    databaseURL: 'https://project-cadastro-revavon-default-rtdb.firebaseio.com',
    storageBucket: 'project-cadastro-revavon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd5eLRAfybgHtCFcqwCoxHMQ_da2Iy7AI',
    appId: '1:97689262276:ios:8694bc650ab5b916cb1191',
    messagingSenderId: '97689262276',
    projectId: 'project-cadastro-revavon',
    databaseURL: 'https://project-cadastro-revavon-default-rtdb.firebaseio.com',
    storageBucket: 'project-cadastro-revavon.appspot.com',
    iosClientId: '97689262276-brr8pe0phjqt0mvso300ck8vtael974b.apps.googleusercontent.com',
    iosBundleId: 'com.jeancc.cadastro.appCadastro',
  );
}
